services:
  postgres:
    image: postgres:16-alpine
    container_name: harddex-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: harddex
      POSTGRES_PASSWORD: harddex123
      POSTGRES_DB: harddex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  firebase:
    image: spine3/firebase-emulator
    container_name: harddex-firebase
    restart: unless-stopped
    ports:
      - "4000:4000" # Emulator Suite UI
      - "9099:9099" # Auth Emulator
      - "8080:8080" # Firestore Emulator
      - "9000:9000" # Database Emulator
      - "9199:9199" # Storage Emulator
      - "5001:5001" # Functions Emulator
      - "8085:8085" # PubSub Emulator
    environment:
      GCP_PROJECT: harddex-project
      ENABLE_UI: "true"

volumes:
  postgres_data:
